name: Exam cron
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Log github
        run: echo "$GITHUB"
        env:
          GITHUB: ${{ toJson(github) }}
